AWSTemplateFormatVersion: 2010-09-09
Parameters:
    JiteshArtifactsBucket:
        Type: String
        Default: artifacts.bucket
        Description: S3 Bucket Name for CodeBuild Artifacts
    JiteshDevBucket:
        Type: String
        Default: dev.bucket
        Description: S3 Bucket Name for Dev environment.
    JiteshStagingBucket:
        Type: String
        Default: staging.bucket
        Description: S3 Bucket Name for Staging environment
    JiteshProductionBucket:
        Type: String
        Default: production.bucket
        Description: S3 Bucket Name for Production environment

Resources:

    # S3 Bucket for build artifacts
    BuildJiteshArtifactsBucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: Private
          BucketName: !Sub '${JiteshArtifactsBucket}'

    # S3 Bucket for Dev environment
    JiteshDevS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: Private
          BucketName: !Sub '${JiteshDevBucket}'
        DependsOn: "BuildJiteshArtifactsBucket"

    # S3 Bucket for Staging environment
    JiteshStagingS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: Private
          BucketName: !Sub '${JiteshStagingBucket}'
        DependsOn: "JiteshDevS3Bucket"

    # S3 Bucket for Production environment
    JiteshProductionS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: Private
          BucketName: !Sub '${JiteshProductionBucket}'
        DependsOn: "jiteshStagingS3Bucket"
